package z:refillguard-auth@0.1.0;

world refillguard-auth {
  export contracts;
}

interface contracts {
  record generic-input {
    input: option<list<u8>>,
    user-profile: option<list<u8>>,
    context: option<list<u8>>,
  }

  authorize-purchase: func(req: generic-input) -> result<list<u8>, string>;
}
